sudo: false

language: node_js

node_js:
  - node

install:
  - npm install mocha
  - npm install chai
  - npm install chai-http
  - npm install ejs
  - npm install express
  - npm install mongoose

script:
  - npm run test